// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: refmon/refmon.proto

package refmon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                          // user_id
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // время жизни токена
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRequest) Reset() {
	*x = IssueRequest{}
	mi := &file_refmon_refmon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRequest) ProtoMessage() {}

func (x *IssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refmon_refmon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRequest.ProtoReflect.Descriptor instead.
func (*IssueRequest) Descriptor() ([]byte, []int) {
	return file_refmon_refmon_proto_rawDescGZIP(), []int{0}
}

func (x *IssueRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type IssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueResponse) Reset() {
	*x = IssueResponse{}
	mi := &file_refmon_refmon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueResponse) ProtoMessage() {}

func (x *IssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refmon_refmon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueResponse.ProtoReflect.Descriptor instead.
func (*IssueResponse) Descriptor() ([]byte, []int) {
	return file_refmon_refmon_proto_rawDescGZIP(), []int{1}
}

func (x *IssueResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_refmon_refmon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refmon_refmon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_refmon_refmon_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_refmon_refmon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refmon_refmon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_refmon_refmon_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_refmon_refmon_proto protoreflect.FileDescriptor

const file_refmon_refmon_proto_rawDesc = "" +
	"\n" +
	"\x13refmon/refmon.proto\x12\x06refmon\"I\n" +
	"\fIssueRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"%\n" +
	"\rIssueResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"'\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\">\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x87\x01\n" +
	"\x10ReferenceMonitor\x124\n" +
	"\x05Issue\x12\x14.refmon.IssueRequest\x1a\x15.refmon.IssueResponse\x12=\n" +
	"\bValidate\x12\x17.refmon.ValidateRequest\x1a\x18.refmon.ValidateResponseB\x17Z\x15token-enforcer/refmonb\x06proto3"

var (
	file_refmon_refmon_proto_rawDescOnce sync.Once
	file_refmon_refmon_proto_rawDescData []byte
)

func file_refmon_refmon_proto_rawDescGZIP() []byte {
	file_refmon_refmon_proto_rawDescOnce.Do(func() {
		file_refmon_refmon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refmon_refmon_proto_rawDesc), len(file_refmon_refmon_proto_rawDesc)))
	})
	return file_refmon_refmon_proto_rawDescData
}

var file_refmon_refmon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_refmon_refmon_proto_goTypes = []any{
	(*IssueRequest)(nil),     // 0: refmon.IssueRequest
	(*IssueResponse)(nil),    // 1: refmon.IssueResponse
	(*ValidateRequest)(nil),  // 2: refmon.ValidateRequest
	(*ValidateResponse)(nil), // 3: refmon.ValidateResponse
}
var file_refmon_refmon_proto_depIdxs = []int32{
	0, // 0: refmon.ReferenceMonitor.Issue:input_type -> refmon.IssueRequest
	2, // 1: refmon.ReferenceMonitor.Validate:input_type -> refmon.ValidateRequest
	1, // 2: refmon.ReferenceMonitor.Issue:output_type -> refmon.IssueResponse
	3, // 3: refmon.ReferenceMonitor.Validate:output_type -> refmon.ValidateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_refmon_refmon_proto_init() }
func file_refmon_refmon_proto_init() {
	if File_refmon_refmon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refmon_refmon_proto_rawDesc), len(file_refmon_refmon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refmon_refmon_proto_goTypes,
		DependencyIndexes: file_refmon_refmon_proto_depIdxs,
		MessageInfos:      file_refmon_refmon_proto_msgTypes,
	}.Build()
	File_refmon_refmon_proto = out.File
	file_refmon_refmon_proto_goTypes = nil
	file_refmon_refmon_proto_depIdxs = nil
}
