// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: refmon/refmon.proto

package refmon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReferenceMonitor_Issue_FullMethodName    = "/refmon.ReferenceMonitor/Issue"
	ReferenceMonitor_Validate_FullMethodName = "/refmon.ReferenceMonitor/Validate"
)

// ReferenceMonitorClient is the client API for ReferenceMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReferenceMonitorClient interface {
	Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*IssueResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type referenceMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewReferenceMonitorClient(cc grpc.ClientConnInterface) ReferenceMonitorClient {
	return &referenceMonitorClient{cc}
}

func (c *referenceMonitorClient) Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*IssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueResponse)
	err := c.cc.Invoke(ctx, ReferenceMonitor_Issue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceMonitorClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, ReferenceMonitor_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferenceMonitorServer is the server API for ReferenceMonitor service.
// All implementations must embed UnimplementedReferenceMonitorServer
// for forward compatibility.
type ReferenceMonitorServer interface {
	Issue(context.Context, *IssueRequest) (*IssueResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedReferenceMonitorServer()
}

// UnimplementedReferenceMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReferenceMonitorServer struct{}

func (UnimplementedReferenceMonitorServer) Issue(context.Context, *IssueRequest) (*IssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Issue not implemented")
}
func (UnimplementedReferenceMonitorServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedReferenceMonitorServer) mustEmbedUnimplementedReferenceMonitorServer() {}
func (UnimplementedReferenceMonitorServer) testEmbeddedByValue()                          {}

// UnsafeReferenceMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferenceMonitorServer will
// result in compilation errors.
type UnsafeReferenceMonitorServer interface {
	mustEmbedUnimplementedReferenceMonitorServer()
}

func RegisterReferenceMonitorServer(s grpc.ServiceRegistrar, srv ReferenceMonitorServer) {
	// If the following call panics, it indicates UnimplementedReferenceMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReferenceMonitor_ServiceDesc, srv)
}

func _ReferenceMonitor_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceMonitorServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceMonitor_Issue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceMonitorServer).Issue(ctx, req.(*IssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceMonitor_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceMonitorServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceMonitor_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceMonitorServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReferenceMonitor_ServiceDesc is the grpc.ServiceDesc for ReferenceMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReferenceMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "refmon.ReferenceMonitor",
	HandlerType: (*ReferenceMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Issue",
			Handler:    _ReferenceMonitor_Issue_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _ReferenceMonitor_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "refmon/refmon.proto",
}
