# Сначала ConstraintTemplate (создаёт CRD)
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requiregvisor
spec:
  crd:
    spec:
      names:
        kind: RequireGVisor
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiregvisor

        violation[{"msg": msg}] {
          not input.review.object.spec.runtimeClassName
          msg := "All pods must use gvisor runtimeClass"
        }

        violation[{"msg": msg}] {
          input.review.object.spec.runtimeClassName != "gvisor"
          msg := sprintf("Forbidden runtimeClass: %v, must be gvisor", [input.review.object.spec.runtimeClassName])
        }
---
# Только потом Constraint (использует созданный CRD)
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireGVisor
metadata:
  name: require-gvisor-domains
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "domain1-untrusted"
      - "domain2-medium"
      - "domain3-tcb"
