// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: security.proto

package security

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityController_CheckInteraction_FullMethodName = "/security.SecurityController/CheckInteraction"
)

// SecurityControllerClient is the client API for SecurityController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityControllerClient interface {
	CheckInteraction(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type securityControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityControllerClient(cc grpc.ClientConnInterface) SecurityControllerClient {
	return &securityControllerClient{cc}
}

func (c *securityControllerClient) CheckInteraction(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, SecurityController_CheckInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityControllerServer is the server API for SecurityController service.
// All implementations must embed UnimplementedSecurityControllerServer
// for forward compatibility.
type SecurityControllerServer interface {
	CheckInteraction(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedSecurityControllerServer()
}

// UnimplementedSecurityControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityControllerServer struct{}

func (UnimplementedSecurityControllerServer) CheckInteraction(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckInteraction not implemented")
}
func (UnimplementedSecurityControllerServer) mustEmbedUnimplementedSecurityControllerServer() {}
func (UnimplementedSecurityControllerServer) testEmbeddedByValue()                            {}

// UnsafeSecurityControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityControllerServer will
// result in compilation errors.
type UnsafeSecurityControllerServer interface {
	mustEmbedUnimplementedSecurityControllerServer()
}

func RegisterSecurityControllerServer(s grpc.ServiceRegistrar, srv SecurityControllerServer) {
	// If the following call panics, it indicates UnimplementedSecurityControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityController_ServiceDesc, srv)
}

func _SecurityController_CheckInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityControllerServer).CheckInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityController_CheckInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityControllerServer).CheckInteraction(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityController_ServiceDesc is the grpc.ServiceDesc for SecurityController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.SecurityController",
	HandlerType: (*SecurityControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInteraction",
			Handler:    _SecurityController_CheckInteraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security.proto",
}
